### PR TITLE
Sang compiler explorer

### PR DESCRIPTION
**Pull request by JorikSchellekens**
The frontend is under `compiler-explorer`.

The js-of-ocaml library exposing the compiler functionality is under `web`.

In order to compile ocaml to js I had to convert the whole thing to a dune project. I think that setup is pretty easy to follow.
However it's missing the rule to actually compiler slang.byte which I'll add later.

Since dune converts warnings to errors I had to make some non-invasive but wide reaching edits to the repo. These mostly eliminate unused variable.

My vim instance is set to nuke trailing whitespace, this adds some noise to this commit.

### CODE REVIEW

**Comment by yallop** [comment]
I've merged some pieces of this separately (#2, #3).

**Comment by yallop** [comment]
I've merged some pieces of this separately (#2, #3).  @JorikSchellekens, could you please rebase the branch?

**Comment by yallop** [comment]
I've merged some more pieces of this (9902cf13, ec91cc88). @JorikSchellekens, you might like to reset your local branch to [compiler-explorer-rebased](https://github.com/yallop/cc_cl_cam_ac_uk/commits/compiler-explorer-rebased) (which simplifies the remaining commit history) and force-push.

**Comment by JorikSchellekens** [comment]
@yallop done

**Pull request merged**
